- name: Install docker dependencies
  apt:
          name:
                  - apt-transport-https
                  - ca-certificates
                  - curl
                  - gnupg2
                  - software-properties-common
                  - python3-pip  
          update_cache: true
          



- name: "Install python docker module"
  pip:
          name:
                  - docker
                  - jsondiff

- name: Add docker key
  apt_key: 
           url: https://download.docker.com/linux/ubuntu/gpg
           state: present


- name: Add docker repository
  apt_repository:
           repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
           state: present


- name: Install docker engine
  apt:
          name:
                  - docker-ce
                  - docker-ce-cli
                  - containerd.io  
          state: latest
          update_cache: true


- name: Add user to the docker group
  user:
          name: "{{ ansible_user }}"
          group: docker
          state: present
